# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtQuickWidgets, QtWidgets

from Downloader import Downloader

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(695, 397)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.linkText = QtWidgets.QLineEdit(self.centralwidget)
        self.linkText.setGeometry(QtCore.QRect(320, 111, 221, 31))
        self.linkText.setObjectName("linkText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(244, 30, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 120, 71, 16))
        self.label_2.setObjectName("label_2")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(320, 250, 93, 28))
        self.downloadButton.setObjectName("downloadButton")
        self.downloadButton.clicked.connect(self.downloadButtonPressed)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(320, 170, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 170, 61, 21))
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(430, 170, 131, 20))
        self.radioButton.setObjectName("radioButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 695, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Youtube Downloader"))
        self.label_2.setText(_translate("MainWindow", "Video Link"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Audio only"))
        self.comboBox.setItemText(1, _translate("MainWindow", "360p"))
        self.comboBox.setItemText(2, _translate("MainWindow", "720p"))
        self.label_3.setText(_translate("MainWindow", "Resolution"))
        self.radioButton.setText(_translate("MainWindow", "Highest resolution"))

    def downloadButtonPressed(self):
        url = self.linkText.text()
        youtube = Downloader(url)

        path = QtWidgets.QFileDialog.getExistingDirectory(self.centralwidget)
        print(str(path))

        # fileOpener = QtWidgets.QFileDialog.getSaveFileName(self.centralwidget, directory=youtube.get_title())
        radioButton = self.radioButton
        comboBox = self.comboBox.itemText(0)
        
        
        if radioButton.isChecked():
            res = youtube.get_highest_resolution()
            youtube.download_video(location=str(path), resolution=str(res))
            self.linkText.setText("")
            
        elif comboBox == "Audio only":
            youtube.download_audio_only(location=str(path))
        
        elif comboBox == "720p":
            youtube.download_video(location=str(path), resolution="720p")
        
        if comboBox == "360p":
            youtube.download_video(location=str(path), resolution="360p")

        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
